cuda_ml_native_symbol_manifest <- function() {
  file.path(pkg_root(), "inst", "native-symbols.txt")
}

cuda_ml_native_registration <- function() {
  file.path(pkg_root(), "tools", "backend", "src", "native_symbols.cpp")
}

write_cuda_ml_native_registration <- function(manifest) {
  stopifnot(nrow(manifest) > 0L)

  declarations <- vapply(
    seq_len(nrow(manifest)),
    function(index) {
      arguments <- rep("SEXP", manifest$arity[[index]])
      paste0(
        "SEXP ",
        manifest$symbol[[index]],
        "(",
        paste(arguments, collapse = ", "),
        ");"
      )
    },
    character(1)
  )
  entries <- vapply(
    seq_len(nrow(manifest)),
    function(index) {
      paste0(
        "    {\"",
        manifest$symbol[[index]],
        "\", (DL_FUNC) &",
        manifest$symbol[[index]],
        ", ",
        manifest$arity[[index]],
        "},"
      )
    },
    character(1)
  )
  code <- c(
    "// Generated by tools/config/utils/native-symbols.R; do not edit.",
    "",
    "#include <R_ext/Rdynload.h>",
    "#include <Rinternals.h>",
    "",
    "extern \"C\" {",
    declarations,
    "}",
    "",
    "static const R_CallMethodDef CallEntries[] = {",
    entries,
    "    {NULL, NULL, 0}",
    "};",
    "",
    "extern \"C\" void R_init_cuda_ml(DllInfo *dll) {",
    "    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);",
    "    R_useDynamicSymbols(dll, FALSE);",
    "}"
  )

  path <- cuda_ml_native_registration()
  existing <- if (file.exists(path)) readLines(path, warn = FALSE) else NULL
  if (!identical(existing, code)) {
    writeLines(code, path)
  }
  invisible(path)
}

rewrite_cuda_ml_rcpp_wrappers <- function(symbols) {
  path <- file.path(pkg_root(), "R", "RcppExports.R")
  stopifnot(file.exists(path), length(symbols) > 0L)

  original <- readLines(path, warn = FALSE)
  pattern <- paste0(
    "^([[:space:]]*)[.]Call\\('(_cuda_ml_[[:alnum:]_]+)', ",
    "PACKAGE = 'cuda[.]ml'(.*)\\)$"
  )
  matches <- regexec(pattern, original)
  values <- regmatches(original, matches)
  generated <- which(lengths(values) == 4L)

  rewritten <- original
  if (length(generated) > 0L) {
    stopifnot(
      length(generated) == length(symbols),
      setequal(vapply(values[generated], `[[`, character(1), 3L), symbols)
    )
    rewritten <- unlist(
      lapply(seq_along(original), function(index) {
        value <- values[[index]]
        if (length(value) != 4L) {
          return(original[[index]])
        }
        indent <- value[[2L]]
        symbol <- value[[3L]]
        arguments <- value[[4L]]
        c(
          paste0(indent, "cuda_ml_require_backend()"),
          paste0(
            indent,
            ".Call(\"",
            symbol,
            "\"",
            arguments,
            ", PACKAGE = \"cuda.ml\")"
          )
        )
      }),
      use.names = FALSE
    )
  }

  stopifnot(
    !any(grepl("[.]Call\\('_cuda_ml_", rewritten)),
    sum(grepl("cuda_ml_require_backend()", rewritten, fixed = TRUE)) ==
      length(symbols),
    sum(grepl("PACKAGE = \"cuda.ml\"", rewritten, fixed = TRUE)) ==
      length(symbols),
    all(vapply(
      symbols,
      function(symbol) {
        sum(grepl(
          paste0(".Call(\"", symbol, "\""),
          rewritten,
          fixed = TRUE
        )) ==
          1L
      },
      logical(1)
    ))
  )
  if (!identical(original, rewritten)) {
    writeLines(rewritten, path)
  }
  invisible(path)
}

generate_cuda_ml_native_symbol_manifest <- function() {
  source <- file.path(
    pkg_root(),
    "tools",
    "backend",
    "src",
    "RcppExports.cpp"
  )
  stopifnot(file.exists(source))

  code <- readLines(source, warn = FALSE)
  pattern <- paste0(
    "^[[:space:]]*RcppExport SEXP (_cuda_ml_[[:alnum:]_]+)",
    "\\(([^)]*)\\)[[:space:]]*\\{[[:space:]]*$"
  )
  matches <- regexec(pattern, code)
  values <- regmatches(code, matches)
  values <- values[lengths(values) == 3L]
  stopifnot(length(values) > 0L)

  arguments <- vapply(values, `[[`, character(1), 3L)
  stopifnot(all(vapply(
    arguments,
    function(value) {
      !nzchar(value) ||
        grepl(
          "^SEXP [[:alnum:]_]+(, SEXP [[:alnum:]_]+)*$",
          value
        )
    },
    logical(1)
  )))

  manifest <- data.frame(
    symbol = vapply(values, `[[`, character(1), 2L),
    arity = vapply(
      arguments,
      function(value) {
        if (nzchar(value)) {
          length(strsplit(value, ", ", fixed = TRUE)[[1L]])
        } else {
          0L
        }
      },
      integer(1)
    ),
    stringsAsFactors = FALSE
  )
  manifest <- manifest[order(manifest$symbol), , drop = FALSE]
  stopifnot(!anyDuplicated(manifest$symbol), all(manifest$arity >= 0L))
  rewrite_cuda_ml_rcpp_wrappers(manifest$symbol)

  path <- cuda_ml_native_symbol_manifest()
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  utils::write.table(
    manifest,
    file = path,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )
  write_cuda_ml_native_registration(manifest)
  invisible(path)
}
