// Generated by tools/config/utils/native-symbols.R; do not edit.

#include <R_ext/Rdynload.h>
#include <Rinternals.h>

extern "C" {
SEXP _cuda_ml_agglomerative_clustering(SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_backend_versions();
SEXP _cuda_ml_cd_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_dbscan(SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_kmeans(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_knn_classifier_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_knn_classifier_predict(SEXP, SEXP, SEXP);
SEXP _cuda_ml_knn_classifier_predict_probabilities(SEXP, SEXP, SEXP);
SEXP _cuda_ml_knn_regressor_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_knn_regressor_predict(SEXP, SEXP, SEXP);
SEXP _cuda_ml_lm_predict(SEXP, SEXP, SEXP);
SEXP _cuda_ml_nvforest_load_model(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_nvforest_model_info(SEXP);
SEXP _cuda_ml_nvforest_predict(SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_nvforest_serialize(SEXP);
SEXP _cuda_ml_nvforest_unserialize(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_ols_fit(SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_pca_fit_transform(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_pca_get_state(SEXP);
SEXP _cuda_ml_pca_inverse_transform(SEXP, SEXP);
SEXP _cuda_ml_pca_set_state(SEXP);
SEXP _cuda_ml_qn_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_qn_predict(SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_qn_predict_probabilities(SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_rf_classifier_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_rf_regressor_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_ridge_fit(SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_sgd_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_svc_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_svc_get_state(SEXP);
SEXP _cuda_ml_svc_predict(SEXP, SEXP, SEXP);
SEXP _cuda_ml_svc_set_state(SEXP);
SEXP _cuda_ml_svr_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_svr_get_state(SEXP);
SEXP _cuda_ml_svr_predict(SEXP, SEXP);
SEXP _cuda_ml_svr_set_state(SEXP);
SEXP _cuda_ml_tsne_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_tsvd_fit_transform(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_tsvd_inverse_transform(SEXP, SEXP);
SEXP _cuda_ml_tsvd_transform(SEXP, SEXP);
SEXP _cuda_ml_umap_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP _cuda_ml_umap_get_state(SEXP);
SEXP _cuda_ml_umap_set_state(SEXP);
SEXP _cuda_ml_umap_transform(SEXP, SEXP);
}

static const R_CallMethodDef CallEntries[] = {
    {"_cuda_ml_agglomerative_clustering", (DL_FUNC) &_cuda_ml_agglomerative_clustering, 5},
    {"_cuda_ml_backend_versions", (DL_FUNC) &_cuda_ml_backend_versions, 0},
    {"_cuda_ml_cd_fit", (DL_FUNC) &_cuda_ml_cd_fit, 9},
    {"_cuda_ml_dbscan", (DL_FUNC) &_cuda_ml_dbscan, 5},
    {"_cuda_ml_kmeans", (DL_FUNC) &_cuda_ml_kmeans, 8},
    {"_cuda_ml_knn_classifier_fit", (DL_FUNC) &_cuda_ml_knn_classifier_fit, 6},
    {"_cuda_ml_knn_classifier_predict", (DL_FUNC) &_cuda_ml_knn_classifier_predict, 3},
    {"_cuda_ml_knn_classifier_predict_probabilities", (DL_FUNC) &_cuda_ml_knn_classifier_predict_probabilities, 3},
    {"_cuda_ml_knn_regressor_fit", (DL_FUNC) &_cuda_ml_knn_regressor_fit, 6},
    {"_cuda_ml_knn_regressor_predict", (DL_FUNC) &_cuda_ml_knn_regressor_predict, 3},
    {"_cuda_ml_lm_predict", (DL_FUNC) &_cuda_ml_lm_predict, 3},
    {"_cuda_ml_nvforest_load_model", (DL_FUNC) &_cuda_ml_nvforest_load_model, 8},
    {"_cuda_ml_nvforest_model_info", (DL_FUNC) &_cuda_ml_nvforest_model_info, 1},
    {"_cuda_ml_nvforest_predict", (DL_FUNC) &_cuda_ml_nvforest_predict, 5},
    {"_cuda_ml_nvforest_serialize", (DL_FUNC) &_cuda_ml_nvforest_serialize, 1},
    {"_cuda_ml_nvforest_unserialize", (DL_FUNC) &_cuda_ml_nvforest_unserialize, 8},
    {"_cuda_ml_ols_fit", (DL_FUNC) &_cuda_ml_ols_fit, 4},
    {"_cuda_ml_pca_fit_transform", (DL_FUNC) &_cuda_ml_pca_fit_transform, 8},
    {"_cuda_ml_pca_get_state", (DL_FUNC) &_cuda_ml_pca_get_state, 1},
    {"_cuda_ml_pca_inverse_transform", (DL_FUNC) &_cuda_ml_pca_inverse_transform, 2},
    {"_cuda_ml_pca_set_state", (DL_FUNC) &_cuda_ml_pca_set_state, 1},
    {"_cuda_ml_qn_fit", (DL_FUNC) &_cuda_ml_qn_fit, 14},
    {"_cuda_ml_qn_predict", (DL_FUNC) &_cuda_ml_qn_predict, 5},
    {"_cuda_ml_qn_predict_probabilities", (DL_FUNC) &_cuda_ml_qn_predict_probabilities, 5},
    {"_cuda_ml_rf_classifier_fit", (DL_FUNC) &_cuda_ml_rf_classifier_fit, 16},
    {"_cuda_ml_rf_regressor_fit", (DL_FUNC) &_cuda_ml_rf_regressor_fit, 16},
    {"_cuda_ml_ridge_fit", (DL_FUNC) &_cuda_ml_ridge_fit, 5},
    {"_cuda_ml_sgd_fit", (DL_FUNC) &_cuda_ml_sgd_fit, 15},
    {"_cuda_ml_svc_fit", (DL_FUNC) &_cuda_ml_svc_fit, 13},
    {"_cuda_ml_svc_get_state", (DL_FUNC) &_cuda_ml_svc_get_state, 1},
    {"_cuda_ml_svc_predict", (DL_FUNC) &_cuda_ml_svc_predict, 3},
    {"_cuda_ml_svc_set_state", (DL_FUNC) &_cuda_ml_svc_set_state, 1},
    {"_cuda_ml_svr_fit", (DL_FUNC) &_cuda_ml_svr_fit, 14},
    {"_cuda_ml_svr_get_state", (DL_FUNC) &_cuda_ml_svr_get_state, 1},
    {"_cuda_ml_svr_predict", (DL_FUNC) &_cuda_ml_svr_predict, 2},
    {"_cuda_ml_svr_set_state", (DL_FUNC) &_cuda_ml_svr_set_state, 1},
    {"_cuda_ml_tsne_fit", (DL_FUNC) &_cuda_ml_tsne_fit, 23},
    {"_cuda_ml_tsvd_fit_transform", (DL_FUNC) &_cuda_ml_tsvd_fit_transform, 7},
    {"_cuda_ml_tsvd_inverse_transform", (DL_FUNC) &_cuda_ml_tsvd_inverse_transform, 2},
    {"_cuda_ml_tsvd_transform", (DL_FUNC) &_cuda_ml_tsvd_transform, 2},
    {"_cuda_ml_umap_fit", (DL_FUNC) &_cuda_ml_umap_fit, 22},
    {"_cuda_ml_umap_get_state", (DL_FUNC) &_cuda_ml_umap_get_state, 1},
    {"_cuda_ml_umap_set_state", (DL_FUNC) &_cuda_ml_umap_set_state, 1},
    {"_cuda_ml_umap_transform", (DL_FUNC) &_cuda_ml_umap_transform, 2},
    {NULL, NULL, 0}
};

extern "C" void R_init_cuda_ml(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
