# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dbscan <- function(x, min_pts, eps, max_bytes_per_batch) {
    .Call(`_cuml4r_dbscan`, x, min_pts, eps, max_bytes_per_batch)
}

.kmeans <- function(x, k, max_iters) {
    .Call(`_cuml4r_kmeans`, x, k, max_iters)
}

.rf_classifier_fit <- function(input, labels, n_trees, bootstrap, max_samples, n_streams, max_depth, max_leaves, max_features, n_bins, min_samples_leaf, min_samples_split, split_criterion, min_impurity_decrease, max_batch_size, verbosity) {
    .Call(`_cuml4r_rf_classifier_fit`, input, labels, n_trees, bootstrap, max_samples, n_streams, max_depth, max_leaves, max_features, n_bins, min_samples_leaf, min_samples_split, split_criterion, min_impurity_decrease, max_batch_size, verbosity)
}

.rf_classifier_predict <- function(model_xptr, input, verbosity) {
    .Call(`_cuml4r_rf_classifier_predict`, model_xptr, input, verbosity)
}

.rf_regressor_fit <- function(input, responses, n_trees, bootstrap, max_samples, n_streams, max_depth, max_leaves, max_features, n_bins, min_samples_leaf, min_samples_split, split_criterion, min_impurity_decrease, max_batch_size, verbosity) {
    .Call(`_cuml4r_rf_regressor_fit`, input, responses, n_trees, bootstrap, max_samples, n_streams, max_depth, max_leaves, max_features, n_bins, min_samples_leaf, min_samples_split, split_criterion, min_impurity_decrease, max_batch_size, verbosity)
}

.rf_regressor_predict <- function(model_xptr, input, verbosity) {
    .Call(`_cuml4r_rf_regressor_predict`, model_xptr, input, verbosity)
}

