# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dbscan <- function(m, min_pts, eps, max_bytes_per_batch) {
    .Call(`_cuml4r_dbscan`, m, min_pts, eps, max_bytes_per_batch)
}

.kmeans <- function(m, k, max_iters) {
    .Call(`_cuml4r_kmeans`, m, k, max_iters)
}

