# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.agglomerative_clustering <- function(x, pairwise_conn, metric, n_neighbors, n_clusters) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_agglomerative_clustering", x, pairwise_conn, metric, n_neighbors, n_clusters, PACKAGE = "cuda.ml")
}

.cd_fit <- function(x, y, fit_intercept, epochs, loss, alpha, l1_ratio, shuffle, tol) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_cd_fit", x, y, fit_intercept, epochs, loss, alpha, l1_ratio, shuffle, tol, PACKAGE = "cuda.ml")
}

.backend_versions <- function() {
    cuda_ml_require_backend()
    .Call("_cuda_ml_backend_versions", PACKAGE = "cuda.ml")
}

.dbscan <- function(x, min_pts, eps, max_bytes_per_batch, verbosity) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_dbscan", x, min_pts, eps, max_bytes_per_batch, verbosity, PACKAGE = "cuda.ml")
}

.kmeans <- function(x, k, max_iters, tol, init_method, centroids, seed, verbosity) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_kmeans", x, k, max_iters, tol, init_method, centroids, seed, verbosity, PACKAGE = "cuda.ml")
}

.knn_classifier_fit <- function(x, y, algo, metric, p, algo_params) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_knn_classifier_fit", x, y, algo, metric, p, algo_params, PACKAGE = "cuda.ml")
}

.knn_classifier_predict <- function(model, x, n_neighbors) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_knn_classifier_predict", model, x, n_neighbors, PACKAGE = "cuda.ml")
}

.knn_classifier_predict_probabilities <- function(model, x, n_neighbors) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_knn_classifier_predict_probabilities", model, x, n_neighbors, PACKAGE = "cuda.ml")
}

.knn_regressor_fit <- function(x, y, algo, metric, p, algo_params) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_knn_regressor_fit", x, y, algo, metric, p, algo_params, PACKAGE = "cuda.ml")
}

.knn_regressor_predict <- function(model, x, n_neighbors) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_knn_regressor_predict", model, x, n_neighbors, PACKAGE = "cuda.ml")
}

.lm_predict <- function(input, coef, intercept) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_lm_predict", input, coef, intercept, PACKAGE = "cuda.ml")
}

.nvforest_load_model <- function(filename, model_type, device, device_id, layout, precision, default_chunk_size, align_bytes) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_nvforest_load_model", filename, model_type, device, device_id, layout, precision, default_chunk_size, align_bytes, PACKAGE = "cuda.ml")
}

.nvforest_model_info <- function(model) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_nvforest_model_info", model, PACKAGE = "cuda.ml")
}

.nvforest_predict <- function(model, input, prediction_type, threshold, chunk_size) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_nvforest_predict", model, input, prediction_type, threshold, chunk_size, PACKAGE = "cuda.ml")
}

.nvforest_serialize <- function(model) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_nvforest_serialize", model, PACKAGE = "cuda.ml")
}

.nvforest_unserialize <- function(bytes, device, device_id, layout, precision, default_chunk_size, align_bytes, averaged_vector_leaf_probabilities) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_nvforest_unserialize", bytes, device, device_id, layout, precision, default_chunk_size, align_bytes, averaged_vector_leaf_probabilities, PACKAGE = "cuda.ml")
}

.ols_fit <- function(x, y, fit_intercept, algo) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_ols_fit", x, y, fit_intercept, algo, PACKAGE = "cuda.ml")
}

.pca_fit_transform <- function(x, tol, n_iters, verbosity, n_components, algo, whiten, transform_input) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_pca_fit_transform", x, tol, n_iters, verbosity, n_components, algo, whiten, transform_input, PACKAGE = "cuda.ml")
}

.pca_inverse_transform <- function(model, x) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_pca_inverse_transform", model, x, PACKAGE = "cuda.ml")
}

.pca_get_state <- function(model) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_pca_get_state", model, PACKAGE = "cuda.ml")
}

.pca_set_state <- function(model_state) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_pca_set_state", model_state, PACKAGE = "cuda.ml")
}

.qn_fit <- function(X, y, n_classes, loss_type, fit_intercept, l1, l2, max_iters, tol, delta, linesearch_max_iters, lbfgs_memory, penalty_normalized, sample_weight) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_qn_fit", X, y, n_classes, loss_type, fit_intercept, l1, l2, max_iters, tol, delta, linesearch_max_iters, lbfgs_memory, penalty_normalized, sample_weight, PACKAGE = "cuda.ml")
}

.qn_predict_probabilities <- function(X, n_classes, coefs, loss_type, fit_intercept) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_qn_predict_probabilities", X, n_classes, coefs, loss_type, fit_intercept, PACKAGE = "cuda.ml")
}

.qn_predict <- function(X, n_classes, coefs, loss_type, fit_intercept) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_qn_predict", X, n_classes, coefs, loss_type, fit_intercept, PACKAGE = "cuda.ml")
}

.rf_classifier_fit <- function(input, labels, n_trees, bootstrap, max_samples, n_streams, max_depth, max_leaves, max_features, n_bins, min_samples_leaf, min_samples_split, split_criterion, min_impurity_decrease, max_batch_size, seed) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_rf_classifier_fit", input, labels, n_trees, bootstrap, max_samples, n_streams, max_depth, max_leaves, max_features, n_bins, min_samples_leaf, min_samples_split, split_criterion, min_impurity_decrease, max_batch_size, seed, PACKAGE = "cuda.ml")
}

.rf_regressor_fit <- function(input, responses, n_trees, bootstrap, max_samples, n_streams, max_depth, max_leaves, max_features, n_bins, min_samples_leaf, min_samples_split, split_criterion, min_impurity_decrease, max_batch_size, seed) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_rf_regressor_fit", input, responses, n_trees, bootstrap, max_samples, n_streams, max_depth, max_leaves, max_features, n_bins, min_samples_leaf, min_samples_split, split_criterion, min_impurity_decrease, max_batch_size, seed, PACKAGE = "cuda.ml")
}

.ridge_fit <- function(x, y, fit_intercept, alpha, algo) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_ridge_fit", x, y, fit_intercept, alpha, algo, PACKAGE = "cuda.ml")
}

.sgd_fit <- function(x, y, fit_intercept, batch_size, epochs, lr_type, eta0, power_t, loss, penalty, alpha, l1_ratio, shuffle, tol, n_iter_no_change) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_sgd_fit", x, y, fit_intercept, batch_size, epochs, lr_type, eta0, power_t, loss, penalty, alpha, l1_ratio, shuffle, tol, n_iter_no_change, PACKAGE = "cuda.ml")
}

.svc_fit <- function(input, labels, cost, kernel, gamma, coef0, degree, tol, max_iter, nochange_steps, cache_size, sample_weights, verbosity) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_svc_fit", input, labels, cost, kernel, gamma, coef0, degree, tol, max_iter, nochange_steps, cache_size, sample_weights, verbosity, PACKAGE = "cuda.ml")
}

.svc_predict <- function(model_xptr, input, predict_class) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_svc_predict", model_xptr, input, predict_class, PACKAGE = "cuda.ml")
}

.svc_get_state <- function(model) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_svc_get_state", model, PACKAGE = "cuda.ml")
}

.svc_set_state <- function(state) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_svc_set_state", state, PACKAGE = "cuda.ml")
}

.svr_fit <- function(X, y, cost, kernel, gamma, coef0, degree, tol, max_iter, nochange_steps, cache_size, epsilon, sample_weights, verbosity) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_svr_fit", X, y, cost, kernel, gamma, coef0, degree, tol, max_iter, nochange_steps, cache_size, epsilon, sample_weights, verbosity, PACKAGE = "cuda.ml")
}

.svr_predict <- function(svr_xptr, X) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_svr_predict", svr_xptr, X, PACKAGE = "cuda.ml")
}

.svr_get_state <- function(model) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_svr_get_state", model, PACKAGE = "cuda.ml")
}

.svr_set_state <- function(state) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_svr_set_state", state, PACKAGE = "cuda.ml")
}

.tsne_fit <- function(x, dim, n_neighbors, theta, epssq, perplexity, perplexity_max_iter, perplexity_tol, early_exaggeration, late_exaggeration, exaggeration_iter, min_gain, pre_learning_rate, post_learning_rate, max_iter, min_grad_norm, pre_momentum, post_momentum, random_state, verbosity, initialize_embeddings, square_distances, algo) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_tsne_fit", x, dim, n_neighbors, theta, epssq, perplexity, perplexity_max_iter, perplexity_tol, early_exaggeration, late_exaggeration, exaggeration_iter, min_gain, pre_learning_rate, post_learning_rate, max_iter, min_grad_norm, pre_momentum, post_momentum, random_state, verbosity, initialize_embeddings, square_distances, algo, PACKAGE = "cuda.ml")
}

.tsvd_fit_transform <- function(x, tol, n_iters, verbosity, n_components, algo, transform_input) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_tsvd_fit_transform", x, tol, n_iters, verbosity, n_components, algo, transform_input, PACKAGE = "cuda.ml")
}

.tsvd_transform <- function(model, x) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_tsvd_transform", model, x, PACKAGE = "cuda.ml")
}

.tsvd_inverse_transform <- function(model, x) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_tsvd_inverse_transform", model, x, PACKAGE = "cuda.ml")
}

.umap_fit <- function(x, y, n_neighbors, n_components, n_epochs, learning_rate, min_dist, spread, set_op_mix_ratio, local_connectivity, repulsion_strength, negative_sample_rate, transform_queue_size, verbosity, a, b, init, target_n_neighbors, target_metric, target_weight, random_state, deterministic) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_umap_fit", x, y, n_neighbors, n_components, n_epochs, learning_rate, min_dist, spread, set_op_mix_ratio, local_connectivity, repulsion_strength, negative_sample_rate, transform_queue_size, verbosity, a, b, init, target_n_neighbors, target_metric, target_weight, random_state, deterministic, PACKAGE = "cuda.ml")
}

.umap_transform <- function(model, x) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_umap_transform", model, x, PACKAGE = "cuda.ml")
}

.umap_get_state <- function(model) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_umap_get_state", model, PACKAGE = "cuda.ml")
}

.umap_set_state <- function(state) {
    cuda_ml_require_backend()
    .Call("_cuda_ml_umap_set_state", state, PACKAGE = "cuda.ml")
}

